; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "InnoSetup.WindowsVersion.TestInstaller"
#define MyAppVersion "1.0"
#define MyAppPublisher "tee"
#define MyAppExeName "InnoSetup.WindowsVersion.TestInstaller.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A4AF6401-4A0B-4178-8392-BAA40B3B2FE8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
CreateAppDir=no
; This installer ships no files and only runs the [Code] self-tests. With
; CreateAppDir=no the {app} dir resolves to {win}, so leaving the uninstaller
; enabled makes Setup try to write its uninstall data into the Windows
; directory - which fails with "CreateFile failed; code 5. Access is denied"
; under PrivilegesRequired=lowest. Disabling the uninstaller avoids that.
Uninstallable=no
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=WindowsVersionTestInstaller
OutputBaseFilename=WindowsVersionTestInstaller
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Code]
#include "..\WindowsVersion.iss"

procedure CheckResult(const AResult, AExpectedResult: Boolean; const AMessage: string);
begin
  // On failure, show an explicit error box (even when silent) and abort Setup
  // (non-zero exit code), so a real problem is never missed.
  if AResult <> AExpectedResult then
    RaiseException('Test failed: "' + AMessage + '" (got ' + IfThenStr(AResult, 'True', 'False')
      + ', expected ' + IfThenStr(AExpectedResult, 'True', 'False') + ')');
end;

var
  GOSMajor: Integer;
  GOSMinor: Integer;
  GOSBuild: Integer;
  GIsServer: Boolean;
  GResultText: string;   // shown on the Finished page when all checks pass

// --- Small display helpers for the demo summary ---

function YesNo(const AValue: Boolean): string;
begin
  Result := IfThenStr(AValue, 'Yes', 'No');
end;

function Pad2(const AValue: Integer): string;
begin
  Result := IntToStr(AValue);
  if Length(Result) < 2 then
    Result := '0' + Result;
end;

// YYYYMMDD integer -> 'YYYY-MM-DD' (or a word when unknown / not announced).
function YmdToStr(const AYmd: Integer): string;
begin
  if AYmd <= 0 then
    Result := 'unknown (TBA)'
  else
    Result := IntToStr(AYmd div 10000) + '-' + Pad2((AYmd div 100) mod 100) + '-' + Pad2(AYmd mod 100);
end;

function FamilyStr: string;
begin
  if IsWindows11 then
    Result := 'Windows 11'
  else if IsWindows10 then
    Result := 'Windows 10'
  else
    Result := 'pre-Windows 10 / other';
end;

// "<date>  (N units left)" / "<date>  (ended N units ago)" / "unknown (TBA)".
function SupportPhrase(const AEndYmd, ATodayYmd: Integer): string;
begin
  if AEndYmd <= 0 then
    Result := 'unknown (TBA)'
  else if IsSupportEnded(AEndYmd, ATodayYmd) then
    Result := YmdToStr(AEndYmd) + '  (ended ' + DaysUntilStr(AEndYmd, ATodayYmd) + ' ago)'
  else
    Result := YmdToStr(AEndYmd) + '  (' + DaysUntilStr(AEndYmd, ATodayYmd) + ' left)';
end;

function CompareInt(const A, B: Integer): Integer;
begin
  if A < B then
    Result := -1
  else if A > B then
    Result := 1
  else
    Result := 0;
end;

// Independent reference comparison: "is the OS {method} than the target version".
// Deliberately a separate, simpler implementation than the library so the
// checks actually cross-validate the library instead of restating it.
function ExpectedResult(const ATargetMajor, ATargetMinor, ATargetBuild: Integer;
  const AMethod: TVersionCompareMethod): Boolean;
var
  LCmp: Integer;
begin
  LCmp := CompareInt(GOSMajor, ATargetMajor);
  
  if LCmp = 0 then
    LCmp := CompareInt(GOSMinor, ATargetMinor);
    
  if LCmp = 0 then
    LCmp := CompareInt(GOSBuild, ATargetBuild);

  if AMethod = vcmOlder then
    Result := LCmp < 0
  else if AMethod = vcmOlderOrEqual then
    Result := LCmp <= 0
  else if AMethod = vcmEqual then
    Result := LCmp = 0
  else if AMethod = vcmNewerOrEqual then
    Result := LCmp >= 0
  else
    Result := LCmp > 0;
end;

procedure CheckOneMethod(const AName: string; const ATargetMajor, ATargetMinor, ATargetBuild: Integer;
  const AServerSku: Boolean; const AMethod: TVersionCompareMethod; const AActual: Boolean);
var
  LExpected: Boolean;
begin
  LExpected := ExpectedResult(ATargetMajor, ATargetMinor, ATargetBuild, AMethod);

  // Server helpers additionally require the OS to be a Server SKU.
  if AServerSku then
    LExpected := LExpected and GIsServer;

  CheckResult(AActual, LExpected, AName);
end;

// Verifies all five compare methods of one helper against the detected OS.
// The caller passes the helper's own build number and its five results.
procedure VerifyHelper(const AName: string; const ATargetMajor, ATargetMinor, ATargetBuild: Integer;
  const AServerSku: Boolean; const AOlder, AOlderOrEqual, AEqual, ANewerOrEqual, ANewer: Boolean);
begin
  CheckOneMethod(AName + '(vcmOlder)', ATargetMajor, ATargetMinor, ATargetBuild, AServerSku, vcmOlder, AOlder);
  CheckOneMethod(AName + '(vcmOlderOrEqual)', ATargetMajor, ATargetMinor, ATargetBuild, AServerSku, vcmOlderOrEqual, AOlderOrEqual);
  CheckOneMethod(AName + '(vcmEqual)', ATargetMajor, ATargetMinor, ATargetBuild, AServerSku, vcmEqual, AEqual);
  CheckOneMethod(AName + '(vcmNewerOrEqual)', ATargetMajor, ATargetMinor, ATargetBuild, AServerSku, vcmNewerOrEqual, ANewerOrEqual);
  CheckOneMethod(AName + '(vcmNewer)', ATargetMajor, ATargetMinor, ATargetBuild, AServerSku, vcmNewer, ANewer);
end;

procedure CheckStr(const AActual, AExpected, AName: string);
begin
  if AActual <> AExpected then
    RaiseException('Test failed: "' + AName + '" (got "' + AActual + '", expected "' + AExpected + '")');
end;

// Switches the library onto a FAKE OS version and keeps the installer's own
// snapshot in sync, so VerifyHelper's expectations are computed against the
// same fake. Also resets the fake product type to 0 (unknown) so edition/track
// resolution never falls through to the REAL GetProductInfo of the box running
// the installer - checks below stay deterministic on any machine. Individual
// checks override the product type / suite mask afterwards as needed.
procedure UseFakeOS(const AMajor, AMinor, ABuild: Integer; const AServer: Boolean);
begin
  SetFakeWindowsVersion(AMajor, AMinor, ABuild, AServer);
  SetFakeWindowsProductType(0);
  GOSMajor := AMajor;
  GOSMinor := AMinor;
  GOSBuild := ABuild;
  GIsServer := AServer;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  LOSVersion: TWindowsVersion;
  LToday: Integer;
  LMajor, LMinor, LBuild: Integer;
begin
  case CurStep of
    ssInstall:
      begin
        // Snapshot the running OS once; every helper is verified RELATIVE to it,
        // so this installer keeps passing as new Windows builds ship (instead of
        // the old hard-coded expectations that assumed one specific dev machine).
        GetWindowsVersionEx(LOSVersion);
        GOSMajor := LOSVersion.Major;
        GOSMinor := LOSVersion.Minor;
        GOSBuild := LOSVersion.Build;
        GIsServer := IsWindowsServer;

        // Desktop releases
        VerifyHelper('IsWin7', 6, 1, 7601, False,
          IsWin7(vcmOlder), IsWin7(vcmOlderOrEqual), IsWin7(vcmEqual), IsWin7(vcmNewerOrEqual), IsWin7(vcmNewer));
        VerifyHelper('IsWin8', 6, 2, 9200, False,
          IsWin8(vcmOlder), IsWin8(vcmOlderOrEqual), IsWin8(vcmEqual), IsWin8(vcmNewerOrEqual), IsWin8(vcmNewer));
        VerifyHelper('IsWin81', 6, 3, 9600, False,
          IsWin81(vcmOlder), IsWin81(vcmOlderOrEqual), IsWin81(vcmEqual), IsWin81(vcmNewerOrEqual), IsWin81(vcmNewer));
        VerifyHelper('IsWin10_1607', 10, 0, 14393, False,
          IsWin10_1607(vcmOlder), IsWin10_1607(vcmOlderOrEqual), IsWin10_1607(vcmEqual), IsWin10_1607(vcmNewerOrEqual), IsWin10_1607(vcmNewer));
        VerifyHelper('IsWin10_1809', 10, 0, 17763, False,
          IsWin10_1809(vcmOlder), IsWin10_1809(vcmOlderOrEqual), IsWin10_1809(vcmEqual), IsWin10_1809(vcmNewerOrEqual), IsWin10_1809(vcmNewer));
        VerifyHelper('IsWin10_1903', 10, 0, 18362, False,
          IsWin10_1903(vcmOlder), IsWin10_1903(vcmOlderOrEqual), IsWin10_1903(vcmEqual), IsWin10_1903(vcmNewerOrEqual), IsWin10_1903(vcmNewer));
        VerifyHelper('IsWin10_2004', 10, 0, 19041, False,
          IsWin10_2004(vcmOlder), IsWin10_2004(vcmOlderOrEqual), IsWin10_2004(vcmEqual), IsWin10_2004(vcmNewerOrEqual), IsWin10_2004(vcmNewer));
        VerifyHelper('IsWin10_21H1', 10, 0, 19043, False,
          IsWin10_21H1(vcmOlder), IsWin10_21H1(vcmOlderOrEqual), IsWin10_21H1(vcmEqual), IsWin10_21H1(vcmNewerOrEqual), IsWin10_21H1(vcmNewer));
        VerifyHelper('IsWin10_21H2', 10, 0, 19044, False,
          IsWin10_21H2(vcmOlder), IsWin10_21H2(vcmOlderOrEqual), IsWin10_21H2(vcmEqual), IsWin10_21H2(vcmNewerOrEqual), IsWin10_21H2(vcmNewer));
        VerifyHelper('IsWin10_22H2', 10, 0, 19045, False,
          IsWin10_22H2(vcmOlder), IsWin10_22H2(vcmOlderOrEqual), IsWin10_22H2(vcmEqual), IsWin10_22H2(vcmNewerOrEqual), IsWin10_22H2(vcmNewer));
        VerifyHelper('IsWin11_21H2', 10, 0, 22000, False,
          IsWin11_21H2(vcmOlder), IsWin11_21H2(vcmOlderOrEqual), IsWin11_21H2(vcmEqual), IsWin11_21H2(vcmNewerOrEqual), IsWin11_21H2(vcmNewer));
        VerifyHelper('IsWin11_22H2', 10, 0, 22621, False,
          IsWin11_22H2(vcmOlder), IsWin11_22H2(vcmOlderOrEqual), IsWin11_22H2(vcmEqual), IsWin11_22H2(vcmNewerOrEqual), IsWin11_22H2(vcmNewer));
        VerifyHelper('IsWin11_23H2', 10, 0, 22631, False,
          IsWin11_23H2(vcmOlder), IsWin11_23H2(vcmOlderOrEqual), IsWin11_23H2(vcmEqual), IsWin11_23H2(vcmNewerOrEqual), IsWin11_23H2(vcmNewer));
        VerifyHelper('IsWin11_24H2', 10, 0, 26100, False,
          IsWin11_24H2(vcmOlder), IsWin11_24H2(vcmOlderOrEqual), IsWin11_24H2(vcmEqual), IsWin11_24H2(vcmNewerOrEqual), IsWin11_24H2(vcmNewer));
        VerifyHelper('IsWin11_25H2', 10, 0, 26200, False,
          IsWin11_25H2(vcmOlder), IsWin11_25H2(vcmOlderOrEqual), IsWin11_25H2(vcmEqual), IsWin11_25H2(vcmNewerOrEqual), IsWin11_25H2(vcmNewer));
        VerifyHelper('IsWin11_26H2', 10, 0, 26300, False,
          IsWin11_26H2(vcmOlder), IsWin11_26H2(vcmOlderOrEqual), IsWin11_26H2(vcmEqual), IsWin11_26H2(vcmNewerOrEqual), IsWin11_26H2(vcmNewer));

        // Server releases (only meaningful on a Server SKU; verified as such)
        VerifyHelper('IsWinServer2008r2', 6, 1, 7601, True,
          IsWinServer2008r2(vcmOlder), IsWinServer2008r2(vcmOlderOrEqual), IsWinServer2008r2(vcmEqual), IsWinServer2008r2(vcmNewerOrEqual), IsWinServer2008r2(vcmNewer));
        VerifyHelper('IsWinServer2012', 6, 2, 9200, True,
          IsWinServer2012(vcmOlder), IsWinServer2012(vcmOlderOrEqual), IsWinServer2012(vcmEqual), IsWinServer2012(vcmNewerOrEqual), IsWinServer2012(vcmNewer));
        VerifyHelper('IsWinServer2012r2', 6, 3, 9600, True,
          IsWinServer2012r2(vcmOlder), IsWinServer2012r2(vcmOlderOrEqual), IsWinServer2012r2(vcmEqual), IsWinServer2012r2(vcmNewerOrEqual), IsWinServer2012r2(vcmNewer));
        VerifyHelper('IsWinServer2016', 10, 0, 14393, True,
          IsWinServer2016(vcmOlder), IsWinServer2016(vcmOlderOrEqual), IsWinServer2016(vcmEqual), IsWinServer2016(vcmNewerOrEqual), IsWinServer2016(vcmNewer));
        VerifyHelper('IsWinServer2016_1709', 10, 0, 16299, True,
          IsWinServer2016_1709(vcmOlder), IsWinServer2016_1709(vcmOlderOrEqual), IsWinServer2016_1709(vcmEqual), IsWinServer2016_1709(vcmNewerOrEqual), IsWinServer2016_1709(vcmNewer));
        VerifyHelper('IsWinServer2016_1803', 10, 0, 17134, True,
          IsWinServer2016_1803(vcmOlder), IsWinServer2016_1803(vcmOlderOrEqual), IsWinServer2016_1803(vcmEqual), IsWinServer2016_1803(vcmNewerOrEqual), IsWinServer2016_1803(vcmNewer));
        VerifyHelper('IsWinServer2019', 10, 0, 17763, True,
          IsWinServer2019(vcmOlder), IsWinServer2019(vcmOlderOrEqual), IsWinServer2019(vcmEqual), IsWinServer2019(vcmNewerOrEqual), IsWinServer2019(vcmNewer));
        VerifyHelper('IsWinServer2019_1903', 10, 0, 18362, True,
          IsWinServer2019_1903(vcmOlder), IsWinServer2019_1903(vcmOlderOrEqual), IsWinServer2019_1903(vcmEqual), IsWinServer2019_1903(vcmNewerOrEqual), IsWinServer2019_1903(vcmNewer));
        VerifyHelper('IsWinServer2022', 10, 0, 20348, True,
          IsWinServer2022(vcmOlder), IsWinServer2022(vcmOlderOrEqual), IsWinServer2022(vcmEqual), IsWinServer2022(vcmNewerOrEqual), IsWinServer2022(vcmNewer));
        VerifyHelper('IsWinServer_23H2', 10, 0, 25398, True,
          IsWinServer_23H2(vcmOlder), IsWinServer_23H2(vcmOlderOrEqual), IsWinServer_23H2(vcmEqual), IsWinServer_23H2(vcmNewerOrEqual), IsWinServer_23H2(vcmNewer));
        VerifyHelper('IsWinServer2025', 10, 0, 26100, True,
          IsWinServer2025(vcmOlder), IsWinServer2025(vcmOlderOrEqual), IsWinServer2025(vcmEqual), IsWinServer2025(vcmNewerOrEqual), IsWinServer2025(vcmNewer));

        // ----- Deterministic checks against a FAKE OS version -----
        // These do not depend on which Windows the installer runs on, so they
        // verify the detection table and comparisons the same way everywhere
        // (e.g. the 26H2 name below is checked even off a 26H2 machine).

        // Fake: Windows 10 22H2 (10.0.19045)
        UseFakeOS(10, 0, 19045, False);
        CheckStr(WindowsVersionStr, 'Windows 10 22H2', 'Fake name 10.0.19045');
        VerifyHelper('[fake 22H2] IsWin10_22H2', 10, 0, 19045, False,
          IsWin10_22H2(vcmOlder), IsWin10_22H2(vcmOlderOrEqual), IsWin10_22H2(vcmEqual), IsWin10_22H2(vcmNewerOrEqual), IsWin10_22H2(vcmNewer));
        VerifyHelper('[fake 22H2] IsWin10_21H2', 10, 0, 19044, False,
          IsWin10_21H2(vcmOlder), IsWin10_21H2(vcmOlderOrEqual), IsWin10_21H2(vcmEqual), IsWin10_21H2(vcmNewerOrEqual), IsWin10_21H2(vcmNewer));
        VerifyHelper('[fake 22H2] IsWin11_24H2', 10, 0, 26100, False,
          IsWin11_24H2(vcmOlder), IsWin11_24H2(vcmOlderOrEqual), IsWin11_24H2(vcmEqual), IsWin11_24H2(vcmNewerOrEqual), IsWin11_24H2(vcmNewer));

        // Fake: Windows 11 24H2 (10.0.26100)
        UseFakeOS(10, 0, 26100, False);
        CheckStr(WindowsVersionStr, 'Windows 11 24H2', 'Fake name 10.0.26100');
        VerifyHelper('[fake 24H2] IsWin11_24H2', 10, 0, 26100, False,
          IsWin11_24H2(vcmOlder), IsWin11_24H2(vcmOlderOrEqual), IsWin11_24H2(vcmEqual), IsWin11_24H2(vcmNewerOrEqual), IsWin11_24H2(vcmNewer));
        VerifyHelper('[fake 24H2] IsWin11_26H2', 10, 0, 26300, False,
          IsWin11_26H2(vcmOlder), IsWin11_26H2(vcmOlderOrEqual), IsWin11_26H2(vcmEqual), IsWin11_26H2(vcmNewerOrEqual), IsWin11_26H2(vcmNewer));
        VerifyHelper('[fake 24H2] IsWin10_22H2', 10, 0, 19045, False,
          IsWin10_22H2(vcmOlder), IsWin10_22H2(vcmOlderOrEqual), IsWin10_22H2(vcmEqual), IsWin10_22H2(vcmNewerOrEqual), IsWin10_22H2(vcmNewer));

        // Fake: Windows 11 26H2 (10.0.26300) - detection verified off a 26H2 box too
        UseFakeOS(10, 0, 26300, False);
        CheckStr(WindowsVersionStr, 'Windows 11 26H2', 'Fake name 10.0.26300');
        VerifyHelper('[fake 26H2] IsWin11_26H2', 10, 0, 26300, False,
          IsWin11_26H2(vcmOlder), IsWin11_26H2(vcmOlderOrEqual), IsWin11_26H2(vcmEqual), IsWin11_26H2(vcmNewerOrEqual), IsWin11_26H2(vcmNewer));

        // Fake: Windows 7 SP1 (6.1.7601)
        UseFakeOS(6, 1, 7601, False);
        CheckStr(WindowsVersionStr, 'Windows 7 SP1', 'Fake name 6.1.7601');
        VerifyHelper('[fake Win7] IsWin7', 6, 1, 7601, False,
          IsWin7(vcmOlder), IsWin7(vcmOlderOrEqual), IsWin7(vcmEqual), IsWin7(vcmNewerOrEqual), IsWin7(vcmNewer));
        VerifyHelper('[fake Win7] IsWin10_22H2', 10, 0, 19045, False,
          IsWin10_22H2(vcmOlder), IsWin10_22H2(vcmOlderOrEqual), IsWin10_22H2(vcmEqual), IsWin10_22H2(vcmNewerOrEqual), IsWin10_22H2(vcmNewer));

        // Fake: Windows Server 2022 (10.0.20348, Server SKU)
        UseFakeOS(10, 0, 20348, True);
        CheckStr(WindowsVersionStr, 'Windows Server 2022', 'Fake name 10.0.20348 (server)');
        VerifyHelper('[fake Srv2022] IsWinServer2022', 10, 0, 20348, True,
          IsWinServer2022(vcmOlder), IsWinServer2022(vcmOlderOrEqual), IsWinServer2022(vcmEqual), IsWinServer2022(vcmNewerOrEqual), IsWinServer2022(vcmNewer));
        VerifyHelper('[fake Srv2022] IsWin11_24H2', 10, 0, 26100, False,
          IsWin11_24H2(vcmOlder), IsWin11_24H2(vcmOlderOrEqual), IsWin11_24H2(vcmEqual), IsWin11_24H2(vcmNewerOrEqual), IsWin11_24H2(vcmNewer));

        // String-based comparisons (independent of the OS; partial/whole strings).
        CheckResult(CompareVersionsStr('10.0.19045', '10.0.19045', vcmEqual), True, 'Str 19045 = 19045');
        CheckResult(CompareVersionsStr('10.0.19045', '10.0', vcmEqual), True, 'Str 19045 = 10.0 (build skipped)');
        CheckResult(CompareVersionsStr('10.0', '10.0.19045', vcmEqual), True, 'Str 10.0 = 19045 (build skipped, first operand)');
        CheckResult(CompareVersionsStr('10.0', '10.0.19045', vcmOlder), False, 'Str 10.0 not older than 19045 (build skipped)');
        CheckResult(CompareVersionsStr('10.1.0', '10.5.0.12332', vcmOlder), True, 'Str 10.1.0 older than 10.5.0.12332');
        CheckResult(CompareVersionsStr('10.1.0', '10.5.0.12332', vcmNewer), False, 'Str 10.1.0 not newer than 10.5.0.12332');
        CheckResult(CompareVersionsStr('11', '10', vcmNewer), True, 'Str 11 newer than 10');
        CheckResult(CompareVersionsStr('10.5.0.12332', '10.5.0', vcmEqual), True, 'Str revision part ignored');

        // Home detection via the VER_SUITE_PERSONAL fallback (product type left
        // 0/unknown by UseFakeOS, so GetProductInfo is not consulted).
        UseFakeOS(10, 0, 19045, False);
        SetFakeWindowsSuiteMask(VER_SUITE_PERSONAL);
        CheckResult(IsWindowsHomeEdition, True, 'Fake Home edition (VER_SUITE_PERSONAL fallback)');
        SetFakeWindowsSuiteMask(0);
        CheckResult(IsWindowsHomeEdition, False, 'Fake non-Home edition (no product info, no suite bits)');

        // Security-support-end lookup + check by build + track (OS-independent).
        CheckResult(IsSupportEnded(GetWindowsSecuritySupportEndByBuild(19045, stWorkstation), 20251231), True, 'Win10 22H2 (W) security support ended by 2025-12-31');
        CheckResult(IsSupportEnded(GetWindowsSecuritySupportEndByBuild(19045, stWorkstation), 20250101), False, 'Win10 22H2 (W) still supported on 2025-01-01');
        CheckResult(IsSupportEnded(GetWindowsSecuritySupportEndByBuild(26100, stWorkstation), 20270101), True, 'Win11 24H2 (W) security support ended by 2027-01-01');
        CheckResult(IsSupportEnded(GetWindowsSecuritySupportEndByBuild(26100, stEnterprise), 20270101), False, 'Win11 24H2 (E) still supported on 2027-01-01');
        CheckResult(IsSupportEnded(GetWindowsSecuritySupportEndByBuild(26100, stServer), 20300101), False, 'Server 2025 (build 26100) still supported on 2030-01-01');
        CheckResult(IsSupportEnded(GetWindowsSecuritySupportEndByBuild(20348, stServer), 20320101), True, 'Server 2022 security support ended by 2032-01-01');

        // Edition detection from GetProductInfo (fake product type), and the
        // track it selects.
        UseFakeOS(10, 0, 26100, False);              // Windows 11 24H2 client
        SetFakeWindowsProductType(4);                // PRODUCT_ENTERPRISE
        CheckResult(GetWindowsEdition = weEnterprise, True, 'Fake Enterprise edition detected');
        CheckResult(GetCurrentSupportTrack = stEnterprise, True, 'Enterprise -> Enterprise support track');
        CheckResult(IsWindowsSecuritySupportEnded(20270601), False, 'Enterprise 24H2 still supported 2027-06 (E track)');
        SetFakeWindowsProductType(48);               // PRODUCT_PROFESSIONAL
        CheckResult(GetWindowsEdition = weProfessional, True, 'Fake Professional edition detected');
        CheckResult(GetCurrentSupportTrack = stWorkstation, True, 'Professional -> Workstation support track');
        CheckResult(IsWindowsSecuritySupportEnded(20270601), True, 'Professional 24H2 past support 2027-06 (W track)');

        // Running-OS predicates + the day-slack rule (fake OS + fixed "today").
        UseFakeOS(10, 0, 19045, False);  // pretend this box is Windows 10 22H2
        CheckResult(IsWindowsSecuritySupportEnded(20260101), True, 'Fake 22H2: security support ended by 2026-01-01');
        CheckResult(IsWindowsSecuritySupportEnded(20250101), False, 'Fake 22H2: still in security support on 2025-01-01');
        // "Block only once security support ended more than 100 days ago":
        //   22H2 security end = 2025-10-14; +100 days ~ 2026-01-22.
        CheckResult(IsPastWithSlackDays(GetWindowsSecuritySupportEnd, 20260101, 100), False, 'Fake 22H2: within 100-day grace on 2026-01-01');
        CheckResult(IsPastWithSlackDays(GetWindowsSecuritySupportEnd, 20260201, 100), True, 'Fake 22H2: past 100-day grace on 2026-02-01');
        // Server SKU resolves to the Server track automatically.
        UseFakeOS(10, 0, 20348, True);   // pretend Windows Server 2022
        CheckResult(IsWindowsSecuritySupportEnded(20320101), True, 'Fake Server 2022: security support ended by 2032-01-01');
        CheckResult(IsWindowsSecuritySupportEnded(20270101), False, 'Fake Server 2022: still supported on 2027-01-01');
        UseFakeOS(6, 1, 7601, False);    // pretend Windows 7
        CheckResult(IsWindowsSecuritySupportEnded(20200101), True, 'Fake Win7: always past security support');

        // One-call install gate.
        UseFakeOS(10, 0, 19045, False);  // Windows 10 22H2, security end 2025-10-14
        CheckResult(IsWindowsSupported(20250101, 0), True, 'Supported before EOL');
        CheckResult(IsWindowsSupported(20260101, 0), False, 'Unsupported after EOL (no slack)');
        CheckResult(IsWindowsSupported(20260101, 100), True, 'Still within 100-day grace');
        UseFakeOS(6, 1, 7601, False);
        CheckResult(IsWindowsSupported(20200101, 3650), False, 'Pre-Win10 never supported, even with slack');

        // Human-readable durations (DurationStr: "x days" / "x months" /
        // "x years y months"), with localisable unit words.
        CheckStr(DurationStr(5), '5 days', 'Duration 5 days');
        CheckStr(DurationStr(1), '1 day', 'Duration singular day');
        CheckStr(DurationStr(90), '3 months', 'Duration 3 months');
        CheckStr(DurationStr(400), '1 year 1 month', 'Duration 1 year 1 month');
        CheckStr(DurationStr(2432), '6 years 8 months', 'Duration big day count');
        SetDurationUnitWords('paiva', 'paivaa', 'kuukausi', 'kuukautta', 'vuosi', 'vuotta');
        CheckStr(DurationStr(400), '1 vuosi 1 kuukausi', 'Finnish duration words');
        CheckStr(DurationStr(800), '2 vuotta 2 kuukautta', 'Finnish plural year');
        SetDurationUnitWords('day', 'days', 'month', 'months', 'year', 'years');  // restore English

        // Family / accessor + data-staleness helpers.
        UseFakeOS(10, 0, 26100, False);
        CheckResult(IsWindows11, True, 'Build 26100 is Windows 11');
        CheckResult(IsWindows10, False, 'Build 26100 is not Windows 10');
        CheckResult(GetWindowsBuildNumber = 26100, True, 'GetWindowsBuildNumber');
        UseFakeOS(10, 0, 19045, False);
        CheckResult(IsWindows10, True, 'Build 19045 is Windows 10');
        CheckResult(IsWindows11, False, 'Build 19045 is not Windows 11');
        CheckResult(IsWindowsDataStale(20261006, 365), False, 'Snapshot not stale on snapshot day');
        CheckResult(IsWindowsDataStale(20281006, 365), True, 'Snapshot stale after 2 years');

        // Done faking - fall back to the real OS. All checks passed (any
        // failure above would have aborted Setup). Build the summary shown on
        // the Finished page - no success message box.
        ClearFakeWindowsVersion;

        LToday := StrToInt(GetDateTimeString('yyyymmdd', #0, #0));
        GetWindowsVersionParts(LMajor, LMinor, LBuild);

        // Everything the library can report for THIS machine - the Finished page
        // doubles as a live demo you can read before clicking Finish.
        GResultText :=
            'All Windows version self-tests passed.' + #13#10 + #13#10
          + 'What the library reports for this machine:' + #13#10
          + '  Name:             ' + WindowsVersionStr + #13#10
          + '  Version:          ' + IntToStr(LMajor) + '.' + IntToStr(LMinor) + '.' + IntToStr(LBuild) + #13#10
          + '  Family:           ' + FamilyStr + #13#10
          + '  Edition:          ' + WindowsEditionToStr(GetWindowsEdition) + #13#10
          + '  Home edition:     ' + YesNo(IsWindowsHomeEdition) + #13#10
          + '  Server SKU:       ' + YesNo(IsWindowsServer) + #13#10
          + '  Support track:    ' + WindowsSupportTrackToStr(GetCurrentSupportTrack) + #13#10
          + '  Active support:   ' + SupportPhrase(GetWindowsActiveSupportEnd, LToday) + #13#10
          + '  Security support: ' + SupportPhrase(GetWindowsSecuritySupportEnd, LToday) + #13#10
          + '  Still supported:  ' + YesNo(IsWindowsSupported(LToday, 0)) + #13#10
          + '  Support data:     snapshot ' + YmdToStr(WINDOWS_DATA_SNAPSHOT_YMD)
          + ' (stale: ' + YesNo(IsWindowsDataStale(LToday, 365)) + ')';
      end;
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  // Show the detected version and the self-test result on the Finished page's
  // label instead of a message box, so a successful run pops no dialogs. Grow
  // the label to fill the page so the whole demo summary is visible.
  if (CurPageID = wpFinished) and (GResultText <> '') then
  begin
    WizardForm.FinishedLabel.AutoSize := False;
    WizardForm.FinishedLabel.Height :=
      WizardForm.FinishedLabel.Parent.ClientHeight - WizardForm.FinishedLabel.Top - ScaleY(8);
    // Monospace so the space-aligned columns line up (a TLabel ignores tabs).
    WizardForm.FinishedLabel.Font.Name := 'Courier New';
    WizardForm.FinishedLabel.Font.Size := 8;
    WizardForm.FinishedLabel.Caption := GResultText;
  end;
end;
